import Head from "next/head";

import { Inter } from "next/font/google";
import Image from "next/image";
import LandingPage from "@/components/landing_page/LandingPage";
// import styles from '@/styles/Home.module.css'
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });
import { getCookie } from "cookies-next";
import { useRouter } from "next/router";
import { redirect } from "next/navigation";

export default function Home() {
  // const isLogin = getCookie("isLogin");
  // const router = useRouter();

  // if (!isLogin) {
  //   return redirect("/login");
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage></LandingPage>
    </>
  );
}
